"""empty message

Revision ID: bfd03feb67ce
Revises: 
Create Date: 2018-03-21 11:28:26.675364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd03feb67ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('create_time', sa.String(length=64), nullable=True))
    op.add_column('event', sa.Column('creator', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'creator')
    op.drop_column('event', 'create_time')
    # ### end Alembic commands ###
